use alerts;

# Individual Privilege(s) for Roles

insert into roleprivileges
       (name, description)
   values
       ('PRIVILEGE_ADSERVER_ADD', 'Add an AD Server to a cluster'),
       ('PRIVILEGE_ADSERVER_READ', 'List/Get an AD Server on a cluster'),
       ('PRIVILEGE_ADSERVER_UPDATE', 'Update the AD Server on a cluster'),
       ('PRIVILEGE_ADSERVER_DELETE', 'Delete the AD Server on a cluster'),
       ('PRIVILEGE_ADSERVER_SETPASSWORD', 'Change the password to the AD Server on a cluster'),
       ('PRIVILEGE_ADSERVER_TEST', 'Test whether Qumulo Alerts can communicate with an AD Server'),
       ('PRIVILEGE_DEFAULT_CAPACITY_READ', 'List/Get the default thresholds for capacity on a cluster'),
       ('PRIVILEGE_DEFAULT_CAPACITY_UPDATE', 'Update the default thresholds for capacity on a cluster'),
       ('PRIVILEGE_CAPACITY_ADD', 'Add the thresholds for monitoring capacity on a cluster'),
       ('PRIVILEGE_CAPACITY_READ', 'List/Get the thresholds for monitoring capacity on a cluster'),
       ('PRIVILEGE_CAPACITY_UPDATE', 'Update the thresholds for monitoring capacity on a cluster'),
       ('PRIVILEGE_CAPACITY_DELETE', 'Delete the thresholds for monitoring capacity on a cluster'),
       ('PRIVILEGE_CLICKSEND_SERVER_ADD', 'Add a new clicksend server configuration'),
       ('PRIVILEGE_CLICKSEND_SERVER_READ', 'List/Get the clicksend server configuration'),
       ('PRIVILEGE_CLICKSEND_SERVER_UPDATE', 'Update the clicksend server configuration'),
       ('PRIVILEGE_CLICKSEND_SERVER_DELETE', 'Delete the clicksend server configuration'),
       ('PRIVILEGE_CLICKSEND_SERVER_TEST', 'Test connectivity to the clicksend server'),
       ('PRIVILEGE_CLUSTER_ADD', 'Add a cluster to be monitored'),
       ('PRIVILEGE_CLUSTER_READ', 'List/Get a cluster(s) that are being monitored'),
       ('PRIVILEGE_CLUSTER_UPDATE', 'Update a monitored cluster'),
       ('PRIVILEGE_CLUSTER_DELETE', 'Delete a monitored cluster'),
       ('PRIVILEGE_DEFAULT_QUOTA_ADD', 'Add a new default quota'),
       ('PRIVILEGE_DEFAULT_QUOTA_READ', 'List/Get the default quota'),
       ('PRIVILEGE_DEFAULT_QUOTA_UPDATE', 'Update the default quota'),
       ('PRIVILEGE_DEFAULT_QUOTA_DELETE', 'Delete a default quota'),
       ('PRIVILEGE_EMAIL_SERVER_ADD', 'Add a new email server configuration'),
       ('PRIVILEGE_EMAIL_SERVER_READ', 'List/Get the email server configuration'),
       ('PRIVILEGE_EMAIL_SERVER_UPDATE', 'Update the email server configuration'),
       ('PRIVILEGE_EMAIL_SERVER_DELETE', 'Delete the email server configuration'),
       ('PRIVILEGE_EMAIL_SERVER_TEST', 'Test connectivity to the email server'),
       ('PRIVILEGE_EXCHANGE_READ', 'List/Get Exchange connections to consumer containers'),
       ('PRIVILEGE_IFTTT_SERVER_ADD', 'Add a new IFTTT server configuration'),
       ('PRIVILEGE_IFTTT_SERVER_READ', 'List/Get the IFTTT server configuration'),
       ('PRIVILEGE_IFTTT_SERVER_UPDATE', 'Update the IFTTT server configuration'),
       ('PRIVILEGE_IFTTT_SERVER_DELETE', 'Delete the IFTTT server configuration'),
       ('PRIVILEGE_IFTTT_SERVER_TEST', 'Test connectivity to the IFTTT server'),
       ('PRIVILEGE_LANGUAGE_READ', 'List/Get Language translations for messages'),
       ('PRIVILEGE_LOGLEVEL_READ', 'List/Get current Logging Level'),
       ('PRIVILEGE_LOGLEVEL_UPDATE', 'Update current Logging Level'),
       ('PRIVILEGE_METRICS_READ', 'List/Get Metrics => InfluxDB mapping'),
       ('PRIVILEGE_METRICS_UPDATE', 'Update Metrics => InfluxDB mapping'),
       ('PRIVILEGE_NOTIFYEVENTS_READ', 'List/Get a NotifyEvent(s)'),
       ('PRIVILEGE_NOTIFYGROUP_ADD', 'Add a new NotifyGroup'),
       ('PRIVILEGE_NOTIFYGROUP_READ', 'List/Get a NotifyGroup'),
       ('PRIVILEGE_NOTIFYGROUP_UPDATE', 'Update a NotifyGroup'),
       ('PRIVILEGE_NOTIFYGROUP_DELETE', 'Delete a NotifyGroup'),
       ('PRIVILEGE_NOTIFYGROUP_MEMBER_ADD', 'Add a new member to a NotifyGroup'),
       ('PRIVILEGE_NOTIFYGROUP_MEMBER_READ', 'List/Get members in a NotifyGroup'),
       ('PRIVILEGE_NOTIFYGROUP_MEMBER_DELETE', 'Delete a member in a NotifyGroup'),
       ('PRIVILEGE_PLUGINS_READ', 'List/Get plugins used for Collector'),
       ('PRIVILEGE_PLUGINS_UPDATE', 'Update frequency on plugin used for Collector'),
       ('PRIVILEGE_CONTAINERMGMT_ADD', 'Add a new container to be managed by Qumulo Alerts'),
       ('PRIVILEGE_CONTAINERMGMT_READ', 'List/Get containers managed by Qumulo Alerts'),
       ('PRIVILEGE_CONTAINERMGMT_UPDATE', 'Update a container managed by Qumulo Alerts'),
       ('PRIVILEGE_CONTAINERMGMT_DELETE', 'Delete a container managed by Qumulo Alerts'),
       ('PRIVILEGE_QUOTA_ADD', 'Add a new quota to be  managed by Qumulo Alerts'),
       ('PRIVILEGE_QUOTA_READ', 'List/Get quotas managed by Qumulo Alerts'),
       ('PRIVILEGE_QUOTA_UPDATE', 'Update a quota managed by Qumulo Alerts'),
       ('PRIVILEGE_QUOTA_DELETE', 'Delete a quota managed by Qumulo Alerts'),
       ('PRIVILEGE_ROLE_ADD', 'Add a new Role'),
       ('PRIVILEGE_ROLE_READ', 'List/Get a Role'),
       ('PRIVILEGE_ROLE_UPDATE', 'Update a Role'),
       ('PRIVILEGE_ROLE_DELETE', 'Delete a Role'),
       ('PRIVILEGE_ROLE_MEMBER_ADD', 'Add a new member to a Role'),
       ('PRIVILEGE_ROLE_MEMBER_READ', 'List/Get members in a Role'),
       ('PRIVILEGE_ROLE_MEMBER_DELETE', 'Delete a member in a Role'),
       ('PRIVILEGE_ROLEPRIVILEGE_READ', 'List/Get privileges in a Role'),
       ('PRIVILEGE_SOFTQUOTA_ADD', 'Add a new soft quota to be managed by Qumulo Alerts'),
       ('PRIVILEGE_SOFTQUOTA_READ', 'List/Get soft quotas managed by Qumulo Alerts'),
       ('PRIVILEGE_SOFTQUOTA_UPDATE', 'Update a soft quota managed by Qumulo Alerts'),
       ('PRIVILEGE_SOFTQUOTA_DELETE', 'Delete a soft quota managed by Qumulo Alerts'),
       ('PRIVILEGE_USER_ADD', 'Add a new User to be  managed by Qumulo Alerts'),
       ('PRIVILEGE_USER_READ', 'List/Get User(s) managed by Qumulo Alerts'),
       ('PRIVILEGE_USER_UPDATE', 'Update a User managed by Qumulo Alerts'),
       ('PRIVILEGE_USER_DELETE', 'Delete a User managed by Qumulo Alerts'),
       ('PRIVILEGE_USER_CHANGEPASSWORD', 'User allowed to change password');

