version: '3.8'

services:

  AlertsDB:
    image: ghcr.io/qumulo/alertsdb:${QUMULOALERTS_VERSION:-latest}
    hostname: alertsdb
    container_name: AlertsDB
    networks:
      - qumuloalerts
    ports:
      - 3307:3306
    volumes:
      - ./alerts-storage/data/:/var/lib/mysql:rw
      - ./alerts-storage/sql/:/docker-entrypoint-initdb.d/:rw
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    healthcheck:
      test: "mariadb -uroot -p$MARIADB_PASSWORD alerts -e 'select 1'"
      interval: 5s
      retries: 10
    restart: unless-stopped

  InfluxDB:
    image: influxdb:${INFLUXDB_VERSION:-2.6.1}
    hostname: influxdb
    container_name: InfluxDB
    networks:
      - qumuloalerts
    ports:
      - 8086:8086
    volumes:
      - ./influxdb-storage/data:/var/lib/influxdb2:rw
      - ./influxdb-storage/config:/etc/influxdb2:rw
      - ./influxdb-storage/backup:/var/lib/backup:rw
    environment:
      - TZ=Etc/UTC
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_RETENTION=${INFLUXDB_INIT_RETENTION}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_INIT_ADMIN_TOKEN}
      - DOCKER_INFLUXDB_INIT_MODE=${INFLUXDB_INIT_MODE}
    healthcheck:
      test: "curl -f http://localhost:8086/ping"
      interval: 5s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  Grafana:
    image: grafana/grafana-oss:${GRAFANA_VERSION:-10.2.0}
    hostname: grafana
    container_name: Grafana
    networks:
      - qumuloalerts
    ports:
      - 3000:3000
    depends_on:
      InfluxDB:
        condition: service_healthy
    volumes:
      - ./grafana-storage:/var/lib/grafana:rw
      - ./grafana-configs/provisioning/:/etc/grafana/provisioning/:rw
      - ./grafana-configs/grafana.ini:/etc/grafana/grafana.ini:rw
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=${GF_USERS_ALLOW_SIGN_UP}
      - INFLUXDB_TOKEN=${INFLUXDB_INIT_ADMIN_TOKEN}
    restart: unless-stopped
      
  Exchange:
    image: ghcr.io/qumulo/exchange:${QUMULOALERTS_VERSION:-latest}
    hostname: exchange
    container_name: Exchange
    networks:
      - qumuloalerts
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: "rabbitmq-diagnostics check_port_connectivity"
      interval: 30s
      timeout: 30s
      retries: 10
    restart: unless-stopped

  Alerts:
    image: ghcr.io/qumulo/alerts:${QUMULOALERTS_VERSION:-6.3.0}
    hostname: alerts
    container_name: Alerts
    networks:
      - qumuloalerts
    ports:
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      Exchange:
        condition: service_healthy
      AlertsDB:
        condition: service_healthy
      InfluxDB:
        condition: service_healthy
    restart: unless-stopped

networks:
  qumuloalerts:
    external: true
