version: '3.8'

services:

  exchange:
    image: qumulo/exchange:${QUMULOALERTS_VERSION:-0.6.6}
    hostname: exchange
    networks:
      - qumuloalerts
    ports:
      - 5672:5672
      - 15672:15672

  alerts:
    image: qumulo/alerts:${QUMULOALERTS_VERSION:-0.6.6}
    hostname: alerts
    networks:
      - qumuloalerts
    volumes:
      - type: bind
        source: ${ALERTS_CONFIGDIR:-./config/alerts/}
        target: /code/config/alerts/

  email:
    image: qumulo/email:${QUMULOALERTS_VERSION:-0.6.6}
    hostname: email
    networks:
      - qumuloalerts
    volumes:
      - type: bind
        source: ${CONSUMER_CONFIGDIR:-./config/consumer/}
        target: /code/config/consumer/

  ifttt:
    image: qumulo/ifttt:${QUMULOALERTS_VERSION:-0.6.6}
    hostname: ifttt
    networks:
      - qumuloalerts
    volumes:
      - type: bind
        source: ${CONSUMER_CONFIGDIR:-./config/consumer/}
        target: /code/config/consumer/

networks:
  qumuloalerts:
    external: true
