{
 "title": "Cluster Details",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": "from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_node_info\")\n  |> keyValues(keyColumns: [\"cluster_name\"])\n  |> group()\n  |> keep(columns: [\"cluster_name\"])\n  |> distinct(column: \"cluster_name\")"
   },
   {
    "name": "QuotaPath",
    "label": "QuotaPath",
    "query": "from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"alerts_quota_entries\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> keyValues(keyColumns: [\"path\"])\n  |> group()\n  |> keep(columns: [\"path\"])\n  |> distinct(column: \"path\")"
   },
   {
    "name": "ShareName",
    "label": "ShareName",
    "query": "from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"alerts_share_entries\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> keyValues(keyColumns: [\"share_name\"])\n  |> group()\n  |> keep(columns: [\"share_name\"])\n  |> distinct(column: \"share_name\")"
   },
   {
    "name": "ExportPath",
    "label": "ExportPath",
    "query": "from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"alerts_export_entries\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> keyValues(keyColumns: [\"export_path\"])\n  |> group()\n  |> keep(columns: [\"export_path\"])\n  |> distinct(column: \"export_path\")"
   },
   {
    "name": "Node",
    "label": "Node",
    "query": "from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_node_info\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> keyValues(keyColumns: [\"node_id\"])\n  |> group()\n  |> keep(columns: [\"node_id\"])\n  |> distinct(column: \"node_id\")"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Details",
   "type": "table",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "measurement = \"qumulo_info\"\nfields = [\"cluster_name\",\"uuid\",\"max_drive_failures\", \"max_node_failures\", \"platform\",\"service_model\", \"version\"]\nfrom(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == measurement)\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> keyValues(keyColumns: fields)\n  |> group()\n  |> last()\n  |> keep(columns: fields)\n  |> rename(columns: {cluster_name: \"Cluster Name\", uuid: \"UUID\",platform: \"Platform\",max_drive_failures: \"Max Drive Failures\", max_node_failures: \"Max Node Failures\", service_model: \"Service Model\", version: \"Version\"})"
    }
   ]
  },
  {
   "title": "Domain",
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 1 },
   "targets": [
    {
     "query": "measurement = \"alerts_ad_info\"\nfields = [\"domain\",\"base_dn\"]\nfrom(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == measurement)\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> keyValues(keyColumns: fields)\n  |> group()\n  |> last()\n  |> keep(columns: fields)\n  |> rename(columns: {domain: \"Domain\", base_dn: \"Base DN\"})\n\n"
    }
   ]
  },
  {
   "title": "Syslog Server",
   "type": "table",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "query": "measurement = \"alerts_audit_info\"\nfields = [\"server_address\",\"server_port\"]\nfrom(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == measurement)\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> keyValues(keyColumns: fields)\n  |> group()\n  |> last()\n  |> keep(columns: fields)\n  |> rename(columns: {server_address: \"Syslog Server\", server_port: \"Port\"})"
    }
   ]
  },
  { "title": "Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Capacity",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_fs_directory_used_bytes\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> filter(fn: (r) => r[\"usage_type\"] == \"data\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n  |> yield(name: \"last\")\n  "
    },
    {
     "query": "from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_fs_free_bytes\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_fs_directory_used_bytes\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> filter(fn: (r) => r[\"usage_type\"] == \"metadata\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n  |> yield(name: \"last\")\n  "
    },
    {
     "query": "from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_fs_directory_used_bytes\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> filter(fn: (r) => r[\"usage_type\"] == \"snapshot\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n  |> yield(name: \"last\")\n  "
    }
   ]
  },
  {
   "title": "Capacity History",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_fs_directory_used_bytes\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> filter(fn: (r) => r[\"usage_type\"] == \"data\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n  |> yield(name: \"last\")\n  "
    },
    {
     "query": "from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_fs_free_bytes\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_fs_directory_used_bytes\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> filter(fn: (r) => r[\"usage_type\"] == \"metadata\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n  |> yield(name: \"last\")\n  "
    },
    {
     "query": "from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_fs_directory_used_bytes\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> filter(fn: (r) => r[\"usage_type\"] == \"snapshot\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n  |> yield(name: \"last\")\n  "
    }
   ]
  },
  {
   "title": "Data Types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_fs_directory_tree_entries\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> aggregateWindow(every: 5m, fn: mean, createEmpty: false)\n  |> yield(name: \"last\")\n  "
    }
   ]
  },
  {
   "title": "Snapshot Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 6 },
   "targets": [
    {
     "query": "from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_fs_snapshots\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  { "title": "Filesystem Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "query": "from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_protocol_operation_bytes_total_total\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> filter(fn: (r) => r[\"io_type\"] != \"none\")\n  |> group(columns: [\"io_type\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> derivative(nonNegative: true) \n\n"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "query": "from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_protocol_operations_total_total\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> filter(fn: (r) => r[\"io_type\"] != \"none\")\n  |> group(columns: [\"io_type\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> derivative(nonNegative: true)\n\n"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "// Fetch the sum metric and group it\nsumMetric = from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_protocol_operation_latency_seconds_sum\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> group(columns: [\"protocol\", \"io_type\", \"data_type\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> derivative(nonNegative: true)\n  |> rename(columns: {_value: \"sum_value\"})\n\n// Fetch the count metric and group it\ncountMetric = from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_protocol_operation_latency_seconds_count\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> group(columns: [\"protocol\", \"io_type\", \"data_type\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> derivative(nonNegative: true)\n  |> rename(columns: {_value: \"count_value\"})\n\n// Join the metrics\njoinedData = join(\n  tables: {sum: sumMetric, count: countMetric},\n  on: [\"_time\", \"protocol\", \"io_type\", \"data_type\"]\n)\n\n// Calculate the ratio with division by zero handling\nresult = joinedData\n  |> map(fn: (r) => ({\n      _time: r._time,\n      protocol: r.protocol,\n      io_type: r.io_type,\n      data_type: r.data_type,\n      ratio: if r.count_value == 0 then 0.0 else r.sum_value / r.count_value\n  }))\n  |> yield(name: \"latency_ratio\")\n"
    }
   ]
  },
  {
   "title": "Current Active Client Connections",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "Cluster = \"${Cluster}\"\n\n// Define a function to create a dataset for a given protocol\ncreateDatasetForProtocol = (protocol) => {\n  connections = from(bucket: \"Qumulo Alerts Metrics\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_protocol_client_connections_total_total\")\n    |> filter(fn: (r) => r[\"cluster_name\"] == Cluster)\n    |> filter(fn: (r) => r[\"protocol\"] == protocol)\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n\n  disconnections = from(bucket: \"Qumulo Alerts Metrics\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_protocol_client_disconnections_total_total\")\n    |> filter(fn: (r) => r[\"cluster_name\"] == Cluster)\n    |> filter(fn: (r) => r[\"protocol\"] == protocol)\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n\n  return join(\n      tables: {conn: connections, disconn: disconnections},\n      on: [\"_time\", \"cluster_name\", \"protocol\"]\n  )\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value_conn - r._value_disconn, cluster_name: r.cluster_name, protocol: r.protocol }))\n}\n\n// Creating and yielding datasets for each protocol\ncreateDatasetForProtocol(protocol: \"ftp\")\n  |> yield(name: \"ftpData\")\n\ncreateDatasetForProtocol(protocol: \"smb\")\n  |> yield(name: \"smbData\")\n\ncreateDatasetForProtocol(protocol: \"nfs\")\n  |> yield(name: \"nfsData\")\n\ncreateDatasetForProtocol(protocol: \"rest\")\n  |> yield(name: \"restData\")\n\ncreateDatasetForProtocol(protocol: \"s3\")\n  |> yield(name: \"s3Data\")"
    }
   ]
  },
  {
   "title": "Active Client Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 4, "y": 24 },
   "targets": [
    {
     "query": "Cluster = \"${Cluster}\"\n\n// Define a function to create a dataset for a given protocol\ncreateDatasetForProtocol = (protocol) => {\n  connections = from(bucket: \"Qumulo Alerts Metrics\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_protocol_client_connections_total_total\")\n    |> filter(fn: (r) => r[\"cluster_name\"] == Cluster)\n    |> filter(fn: (r) => r[\"protocol\"] == protocol)\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n\n  disconnections = from(bucket: \"Qumulo Alerts Metrics\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_protocol_client_disconnections_total_total\")\n    |> filter(fn: (r) => r[\"cluster_name\"] == Cluster)\n    |> filter(fn: (r) => r[\"protocol\"] == protocol)\n    |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n\n  return join(\n      tables: {conn: connections, disconn: disconnections},\n      on: [\"_time\", \"cluster_name\", \"protocol\"]\n  )\n  |> map(fn: (r) => ({ _time: r._time, _value: r._value_conn - r._value_disconn, cluster_name: r.cluster_name, protocol: r.protocol }))\n}\n\n// Creating and yielding datasets for each protocol\ncreateDatasetForProtocol(protocol: \"ftp\")\n  |> yield(name: \"ftpData\")\n\ncreateDatasetForProtocol(protocol: \"smb\")\n  |> yield(name: \"smbData\")\n\ncreateDatasetForProtocol(protocol: \"nfs\")\n  |> yield(name: \"nfsData\")\n\ncreateDatasetForProtocol(protocol: \"rest\")\n  |> yield(name: \"restData\")\n\ncreateDatasetForProtocol(protocol: \"s3\")\n  |> yield(name: \"s3Data\")"
    }
   ]
  },
  {
   "title": "Protocol Ops",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "query": "from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_protocol_operations_total_total\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> group(columns: [\"op_name\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> derivative(unit: 1s, nonNegative: true) \n  |> yield(name: \"rate\")\n"
    }
   ]
  },
  {
   "title": "Protocol Ops Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "// Fetch the sum metric and group it\nsumMetric = from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_protocol_operation_latency_seconds_sum\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> group(columns: [\"op_name\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> derivative(unit: 1s, nonNegative: true)\n  |> rename(columns: {_value: \"sum_value\"})\n\n// Fetch the count metric and group it\ncountMetric = from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_protocol_operation_latency_seconds_count\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> group(columns: [\"op_name\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> derivative(unit: 1s, nonNegative: true)\n  |> rename(columns: {_value: \"count_value\"})\n\n// Join the metrics\njoinedData = join(\n  tables: {sum: sumMetric, count: countMetric},\n  on: [\"_time\", \"op_name\"]\n)\n\n// Calculate the ratio with division by zero handling\nresult = joinedData\n  |> map(fn: (r) => ({\n      _time: r._time,\n      op_name: r.op_name,\n      ratio: if r.count_value == 0 then 0.0 else r.sum_value / r.count_value\n  }))\n  |> yield(name: \"latency_ratio\")\n"
    }
   ]
  },
  { "title": "Hardware Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Disk Read Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "Cluster = \"${Cluster}\"\n\nlsum = from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_disk_operation_latency_seconds_sum\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == Cluster)\n  |> filter(fn: (r) => r[\"io_type\"] == \"read\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> derivative(nonNegative: true)\n\nlcount = from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_disk_operation_latency_seconds_count\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == Cluster)\n  |> filter(fn: (r) => r[\"io_type\"] == \"read\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> derivative(nonNegative: true)\n\n// Joining and mapping the data\njoin(\n    tables: {lsum: lsum, lcount: lcount},\n    on: [\"_time\", \"cluster_name\", \"node_id\", \"drive_bay\", \"disk_type\", \"io_type\"]\n)\n|> map(fn: (r) => ({ _time: r._time, _value: if r._value_lcount == 0 then 0.0 else r._value_lsum / r._value_lcount, node_id: r.node_id, drive_bay: r.drive_bay, disk_type: r.disk_type, io_type: r.io_type }))"
    }
   ]
  },
  {
   "title": "Disk Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "Cluster = \"${Cluster}\"\n\nlsum = from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_disk_operation_latency_seconds_sum\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == Cluster)\n  |> filter(fn: (r) => r[\"io_type\"] == \"write\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> derivative(nonNegative: true)\n\nlcount = from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_disk_operation_latency_seconds_count\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == Cluster)\n  |> filter(fn: (r) => r[\"io_type\"] == \"write\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> derivative(nonNegative: true)\n\n// Joining and mapping the data\njoin(\n    tables: {lsum: lsum, lcount: lcount},\n    on: [\"_time\", \"cluster_name\", \"node_id\", \"drive_bay\", \"disk_type\", \"io_type\"]\n)\n|> map(fn: (r) => ({ _time: r._time, _value: if r._value_lcount == 0 then 0.0 else r._value_lsum / r._value_lcount, node_id: r.node_id, drive_bay: r.drive_bay, disk_type: r.disk_type, io_type: r.io_type }))"
    }
   ]
  },
  {
   "title": "Network Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "query": "from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_network_interface_transmitted_bytes_total_total\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> derivative(nonNegative: false)\n  |> map(fn: (r) => ({_value: r._value, _time: r._time, _field: \"Transmitted\", interface: r.interface, role: r.role, node_id: r.node_id}))\n  |> yield(name: \"Transmitted\")\n\n  \n"
    },
    {
     "query": "from(bucket: \"Qumulo Alerts Metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_network_interface_received_bytes_total_total\")\r\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\r\n  |> derivative(nonNegative: false)\r\n  |> map(fn: (r) => ({_value: r._value, _time: r._time, _field: \"Received\", interface: r.interface, role: r.role, node_id: r.node_id}))\r\n  |> yield(name: \"Received\")"
    }
   ]
  },
  {
   "title": "Network Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_network_interface_transmit_errors_total_total\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> map(fn: (r) => ({_value: r._value, _time: r._time, _field: \"TX\", interface: r.interface, role: r.role, node_id: r.node_id}))\n  |> yield(name: \"Transmitted\")\n\n  \n"
    },
    {
     "query": "from(bucket: \"Qumulo Alerts Metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_network_interface_receive_errors_total_total\")\r\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\r\n  |> map(fn: (r) => ({_value: r._value, _time: r._time, _field: \"TX\", interface: r.interface, role: r.role, node_id: r.node_id}))\r\n  |> yield(name: \"Received\")"
    }
   ]
  },
  { "title": "AD/LDAP Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "AD Netlogon Request Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "query": "from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_ad_netlogon_requests_total_total\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> group(columns: [\"server_url\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> derivative(unit: 1s, nonNegative: true) \n\n"
    }
   ]
  },
  {
   "title": "AD Netlogon Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "query": "from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_ad_netlogon_request_errors_total_total\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> group(columns: [\"server_url\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> derivative(nonNegative: true) \n\n"
    }
   ]
  },
  {
   "title": "AD Netlogon Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "// Fetch the sum metric and group it\nsumMetric = from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_ad_netlogon_request_latency_seconds_sum\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> group(columns: [\"server_url\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> derivative(unit: 1s, nonNegative: true)\n  |> rename(columns: {_value: \"sum_value\"})\n\n// Fetch the count metric and group it\ncountMetric = from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_ad_netlogon_request_latency_seconds_count\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> group(columns: [\"server_url\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> derivative(unit: 1s, nonNegative: true)\n  |> rename(columns: {_value: \"count_value\"})\n\n// Join the metrics\njoinedData = join(\n  tables: {sum: sumMetric, count: countMetric},\n  on: [\"_time\", \"server_url\"]\n)\n\n// Calculate the ratio with division by zero handling\nresult = joinedData\n  |> map(fn: (r) => ({\n      _time: r._time,\n      server_url: r.server_url,\n      ratio: if r.count_value == 0 then 0.0 else r.sum_value / r.count_value\n  }))\n  |> yield(name: \"latency_ratio\")\n"
    }
   ]
  },
  {
   "title": "LDAP Operation Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "query": "from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_ldap_operations_total_total\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> group(columns: [\"domain_url\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> derivative(unit: 1s, nonNegative: true) \n\n"
    }
   ]
  },
  {
   "title": "LDAP Operation Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "query": "from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_ldap_operation_errors_total_total\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> group(columns: [\"domain_url\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> derivative(nonNegative: true) \n\n"
    }
   ]
  },
  {
   "title": "LDAP Operation Referrals",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "query": "from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_ldap_operation_referrals_total_total\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> group(columns: [\"domain_url\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> derivative(nonNegative: true) \n\n"
    }
   ]
  },
  {
   "title": "LDAP Request Throughput",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "query": "from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_ldap_lookup_requests_total_total\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> group(columns: [\"server_url\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> derivative(unit: 1s, nonNegative: true) \n\n"
    }
   ]
  },
  {
   "title": "LDAP Request Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "query": "from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_ldap_lookup_request_errors_total_total\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> group(columns: [\"server_url\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> derivative(nonNegative: true) \n\n"
    }
   ]
  },
  {
   "title": "LDAP Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "query": "// Fetch the sum metric and group it\nsumMetric = from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_ldap_lookup_request_latency_seconds_sum\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> group(columns: [\"server_url\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> derivative(unit: 1s, nonNegative: true)\n  |> rename(columns: {_value: \"sum_value\"})\n\n// Fetch the count metric and group it\ncountMetric = from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_ldap_lookup_request_latency_seconds_count\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> group(columns: [\"server_url\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> derivative(unit: 1s, nonNegative: true)\n  |> rename(columns: {_value: \"count_value\"})\n\n// Join the metrics\njoinedData = join(\n  tables: {sum: sumMetric, count: countMetric},\n  on: [\"_time\", \"server_url\"]\n)\n\n// Calculate the ratio with division by zero handling\nresult = joinedData\n  |> map(fn: (r) => ({\n      _time: r._time,\n      server_url: r.server_url,\n      ratio: if r.count_value == 0 then 0.0 else r.sum_value / r.count_value\n  }))\n  |> yield(name: \"latency_ratio\")\n"
    }
   ]
  },
  { "title": "Users and Groups", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Local Users",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "query": "measurement = \"alerts_users_info\"\nfields = [\"name\",\"uid\", \"primary_group\", \"sid\"]\nfrom(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == measurement)\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> keyValues(keyColumns: fields)\n  |> group()\n  |> keep(columns: fields)\n  |> unique(column: \"name\")\n  |> rename(columns: {name: \"User Name\", uid: \"UID\", primary_group: \"Primary Group\", sid: \"SID\"})"
    }
   ]
  },
  {
   "title": "Local Groups",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "query": "measurement = \"alerts_groups_info\"\nfields = [\"name\",\"gid\", \"sid\"]\nfrom(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == measurement)\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> keyValues(keyColumns: fields)\n  |> group()\n  |> keep(columns: fields)\n  |> unique(column: \"name\")\n  |> rename(columns: {name: \"Group Name\", gid: \"GID\", sid: \"SID\"})"
    }
   ]
  },
  { "title": "Quotas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Quotas",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "import \"join\"\n\nmeasurement = \"alerts_quota_entries\"\nfields = [\"path\", \"limit\", \"capacity_usage\"]\n\nleft =\n  from(bucket: \"Qumulo Alerts Metrics\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == measurement)\n    |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n    |> filter(fn: (r) => r[\"entry_type\"] == \"capacity_usage\")\n    |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n    |> group()\n    |> unique(column: \"path\")\n\nright =\n  from(bucket: \"Qumulo Alerts Metrics\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == measurement)\n    |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n    |> filter(fn: (r) => r[\"entry_type\"] == \"limit\")\n    |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n    |> group()\n    |> unique(column: \"path\")\n\njoin.full(\n    left: left,\n    right: right,\n    on: (l, r) => l.path == r.path,\n    as: (l, r) => {\n        path = if exists l.path then l.path else r.path\n\n        return {path: path, capacity_usage: l._value, limit: r._value}\n    },\n)\n|> rename(columns: {path: \"Path\", limit: \"Limit\", capacity_usage: \"Capacity Usage\"})"
    }
   ]
  },
  {
   "title": "${QuotaPath}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 86 },
   "repeat": "QuotaPath",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "import \"join\"\n\nmeasurement = \"alerts_quota_entries\"\nfields = [\"path\", \"limit\", \"capacity_usage\"]\n\nleft =\n  from(bucket: \"Qumulo Alerts Metrics\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == measurement)\n    |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n    |> filter(fn: (r) => r[\"path\"] == \"${QuotaPath}\")\n    |> filter(fn: (r) => r[\"entry_type\"] == \"capacity_usage\")\n    |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n    |> group(columns: [\"path\"])\n\nright =\n  from(bucket: \"Qumulo Alerts Metrics\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r[\"_measurement\"] == measurement)\n    |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n    |> filter(fn: (r) => r[\"path\"] == \"${QuotaPath}\")\n    |> filter(fn: (r) => r[\"entry_type\"] == \"limit\")\n    |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n    |> group(columns: [\"path\"])\n\njoin.full(\n    left: left,\n    right: right,\n    on: (l, r) => l.path == r.path and l._time == r._time,\n    as: (l, r) => {\n        time = if exists l._time then l._time else r._time\n        path = if exists l.path then l.path else r.path\n\n        return {_time: time, path: path, capacity_usage: l._value, limit: r._value}\n    },\n)\n|> rename(columns: {path: \"Path\", limit: \"Limit\", capacity_usage: \"Capacity Usage\"})"
    }
   ]
  },
  { "title": "SMB Shares", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "SMB Shares",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "measurement = \"alerts_share_entries\"\nfields = [\"fs_path\",\"share_name\", \"_value\"]\nfrom(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == measurement)\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> filter(fn: (r) => r[\"entry_type\"] == \"capacity\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> group()\n  |> keep(columns: fields)\n  |> unique(column: \"share_name\")\n  |> rename(columns: {fs_path: \"File System Path\", share_name: \"Share Name\", _value: \"Capacity\"})"
    }
   ]
  },
  {
   "title": "${ShareName}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "repeat": "ShareName",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "measurement = \"alerts_share_entries\"\n\n\nfrom(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == measurement)\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> filter(fn: (r) => r[\"share_name\"] == \"${ShareName}\")\n  |> filter(fn: (r) => r[\"entry_type\"] == \"capacity\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "${ShareName}",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
   "repeat": "ShareName",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "measurement = \"alerts_share_entries\"\n\n\nfrom(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == measurement)\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> filter(fn: (r) => r[\"share_name\"] == \"${ShareName}\")\n  |> filter(fn: (r) => r[\"entry_type\"] == \"alternative_data_stream\" or r[\"entry_type\"] == \"file\" or r[\"entry_type\"] == \"directory\" or r[\"entry_type\"] == \"other\" or r[\"entry_type\"] == \"symlink\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")\n"
    }
   ]
  },
  { "title": "NFS Exports", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 } },
  {
   "title": "NFS Exports",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "measurement = \"alerts_export_entries\"\nfields = [\"fs_path\",\"export_path\", \"_value\"]\nfrom(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == measurement)\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> filter(fn: (r) => r[\"entry_type\"] == \"capacity\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> group()\n  |> keep(columns: fields)\n  |> unique(column: \"export_path\")\n  |> rename(columns: {fs_path: \"File System Path\", export_path: \"Export Path\", _value: \"Capacity\"})"
    }
   ]
  },
  {
   "title": "${ExportPath}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 128 },
   "repeat": "ExportPath",
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "measurement = \"alerts_export_entries\"\n\n\nfrom(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == measurement)\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> filter(fn: (r) => r[\"export_path\"] == \"${ExportPath}\")\n  |> filter(fn: (r) => r[\"entry_type\"] == \"capacity\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "${ExportPath}",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 137 },
   "repeat": "ExportPath",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "measurement = \"alerts_export_entries\"\n\n\nfrom(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == measurement)\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> filter(fn: (r) => r[\"export_path\"] == \"${ExportPath}\")\n  |> filter(fn: (r) => r[\"entry_type\"] == \"alternative_data_stream\" or r[\"entry_type\"] == \"file\" or r[\"entry_type\"] == \"directory\" or r[\"entry_type\"] == \"other\" or r[\"entry_type\"] == \"symlink\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "Node Hardware Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 145 } },
  {
   "title": "Node-${Node}",
   "type": "stat",
   "gridPos": { "h": 5, "w": 1, "x": 0, "y": 146 },
   "repeat": "Node",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_quorum_node_is_offline\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> filter(fn: (r) => r[\"node_id\"] == \"${Node}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Node Model",
   "type": "table",
   "gridPos": { "h": 5, "w": 1, "x": 1, "y": 146 },
   "repeat": "Node",
   "targets": [
    {
     "query": "measurement = \"qumulo_node_info\"\nfields = [\"node_model\"]\nfrom(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == measurement)\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> keyValues(keyColumns: fields)\n  |> group()\n  |> last()\n  |> keep(columns: fields)\n  |> rename(columns: {node_model: \"Node Model\"})"
    }
   ]
  },
  {
   "title": "Time Sync",
   "type": "stat",
   "gridPos": { "h": 5, "w": 1, "x": 2, "y": 146 },
   "repeat": "Node",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_time_is_not_synchronizing\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> filter(fn: (r) => r[\"node_id\"] == \"${Node}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "CPU Temp.",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 1, "x": 3, "y": 146 },
   "repeat": "Node",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_cpu_temperature_celsius\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> filter(fn: (r) => r[\"node_id\"] == \"${Node}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Fan Speeds",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 146 },
   "repeat": "Node",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_fan_speed_rpm\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> filter(fn: (r) => r[\"node_id\"] == \"${Node}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Disk Health Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 146 },
   "repeat": "Node",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_disk_is_unhealthy\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> filter(fn: (r) => r[\"node_id\"] == \"${Node}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Disk Endurances",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 14, "y": 146 },
   "repeat": "Node",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_disk_endurance_percent\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> filter(fn: (r) => r[\"node_id\"] == \"${Node}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Memory Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 146 },
   "repeat": "Node",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_memory_correctable_ecc_errors_total_total\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> filter(fn: (r) => r[\"node_id\"] == \"${Node}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({_value: r._value, _time: r._time, _field: \"Correctable\", node_id: r.node_id}))\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: \"Qumulo Alerts Metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_memory_uncorrectable_ecc_errors_total_total\")\r\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\r\n  |> filter(fn: (r) => r[\"node_id\"] == \"${Node}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> map(fn: (r) => ({_value: r._value, _time: r._time, _field: \"Uncorrectable\", node_id: r.node_id}))\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "NIC Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 146 },
   "repeat": "Node",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_network_interface_is_down\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> filter(fn: (r) => r[\"node_id\"] == \"${Node}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Power Supplies",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 146 },
   "repeat": "Node",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"Qumulo Alerts Metrics\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"qumulo_power_supply_is_unhealthy\")\n  |> filter(fn: (r) => r[\"cluster_name\"] == \"${Cluster}\")\n  |> filter(fn: (r) => r[\"node_id\"] == \"${Node}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}